name: pizza
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  badges: ^2.0.3
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/img/

  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/font/SourceSansProRegular.ttf
        - asset: assets/font/SourceSansProSemiBold.ttf
          weight: 600

